kind: pipeline
name: default

steps:
  - name: products-service
    image: plugins/docker
    settings:
      username: kevinbacon
      password: pa55word
      repo: foo/bar
      dockerfile: ./products-service/.docker/products-service.dockerfile
