---
kind: pipeline
name: products-service

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/federation-graphql-rust/products-service
      context: ./products-service
      dockerfile: ./products-service/.docker/products-service.dockerfile
      auto_tag: true
      target: production

---
kind: pipeline
name: acpm-service

steps:
  - name: rust-build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/federation-graphql-rust/acpm-service
      context: ./acpm-service
      dockerfile: ./acpm-service/.docker/acpm-service.dockerfile
      auto_tag: true
      target: production

  - name: postgres-build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/federation-graphql-rust/acpm-postgres
      context: ./acpm-service/.docker
      dockerfile: ./acpm-service/.docker/postgres.dockerfile
      auto_tag: true

---
kind: pipeline
name: identity-service

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/federation-graphql-rust/identity-service
      context: ./identity-service
      dockerfile: ./identity-service/.docker/identity-service.dockerfile
      auto_tag: true
      target: production

# ---
# kind: pipeline
# name: subscription-service
# 
# steps:
#   - name: build
#     image: plugins/docker
#     settings:
#       registry: ghcr.io
#       username: simoneromano96
#       password: 
#         from_secret: token
#       repo: ghcr.io/simoneromano96/federation-graphql-rust/subscription-service
#       context: ./subscription-service
#       dockerfile: ./subscription-service/.docker/subscription-service.dockerfile
#       auto_tag: true
#       target: production

---
kind: pipeline
name: graphql-gateway

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/federation-graphql-rust/graphql-gateway
      context: ./gateway
      dockerfile: ./gateway/.docker/gateway.dockerfile
      auto_tag: true
