kind: pipeline
name: default

steps:
  - name: products-service
    image: plugins/docker
    settings:
      target: production
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/federation-graphql-rust/products-service
      context: ./products-service
      dockerfile: ./products-service/.docker/products-service.dockerfile
