version: "3.6"

services:
  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  postgres:
    image: ghcr.io/simoneromano96/federation-graphql-rust/acpm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: casbin
      POSTGRES_PASSWORD: casbin
      POSTGRES_DB: casbin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  acpm-service:
    image: ghcr.io/simoneromano96/federation-graphql-rust/acpm-service
    restart: unless-stopped
    environment: 
      APP_DATABASE_URL: postgres://casbin:casbin@postgres:5432/casbin
      APP_DATABASE_POOLSIZE: 16
      APP_SERVER_PORT: 80
      APP_DEBUG: "true"
    ports: 
      - 3999:80
    depends_on: 
      - postgres

  graphql-gateway:
    image: ghcr.io/simoneromano96/federation-graphql-rust/graphql-gateway
    restart: unless-stopped
    environment: 
      PORT: 80
      IDENTITY_SERVICE_URL: http://identity-service/graphql
      PRODUCTS_SERVICE_URL: http://products-service/graphql
    ports: 
      - 4000:80
    depends_on: 
      - identity-service
      - products-service

  identity-service:
    image: ghcr.io/simoneromano96/federation-graphql-rust/identity-service
    restart: unless-stopped
    environment: 
      APP_DEBUG: "true"
      APP_DATABASE_URL: mongodb://root:example@mongo:27017/admin
      APP_SERVER_PORT: 80
      APP_REDIS_URL: redis://redis:6379
    ports: 
      - 4001:80
    depends_on: 
      - redis
      - mongo

  products-service:
    image: ghcr.io/simoneromano96/federation-graphql-rust/products-service
    restart: unless-stopped
    environment: 
      APP_DEBUG: "true"
      APP_REDIS_URL: redis://redis:6379
      APP_DATABASE_URL: mongodb://root:example@mongo:27017/admin
      APP_SERVER_PORT: 80
      APP_AUTHORIZATION_URL: http://acpm-service/api/v1/authorization/is-authorized
      APP_AUTH_USERNAME: products-service
      APP_AUTH_PASSWORD: password
    ports: 
      - 4002:80
    depends_on: 
      - acpm-service
      - redis
      - mongo

  #subscription-service:
  #  image: ghcr.io/simoneromano96/federation-graphql-rust/subscription-service
  #  restart: unless-stopped
  #  environment: 
  #    APP_DATABASE_URL: mongodb://root:example@mongo:27017/admin
  #    APP_SERVER_PORT: 80
  #  ports: 
  #    - 4003:80

volumes:
  postgres_data:
