version: '3'

services:
  db:
    build: 
      context: ./.docker
      dockerfile: postgres.dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: casbin
      POSTGRES_PASSWORD: casbin
      POSTGRES_DB: casbin
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes: 
  postgres_data:
