version: '3'

services:
  postgres:
    build: 
      context: ./.docker
      dockerfile: postgres.dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: casbin
      POSTGRES_PASSWORD: casbin
      POSTGRES_DB: casbin
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  app:
    build: 
      context: .
      dockerfile: ./.docker/acpm-service.dockerfile
    restart: unless-stopped
    environment: 
      APP_DATABASE_URL: postgres://casbin:casbin@postgres:5432/casbin
      APP_DATABASE_POOLSIZE: 16
      APP_SERVER_PORT: 80
    ports: 
      - 3999:80
    

volumes: 
  postgres_data:
